### ISSUE TITLE
Сопоставление имён файлов и названий книг

### ISSUE THREAD

**Issue by iprst** [terratensor/book-parser#27]
На текущий момент обработано 6340 книг из 7733.

**Comment by iprst** [comment]
Из первоначальной 7733 библиотеки переименованы 6684 книги, осталось около 800. 

Файлы html во многом дублируют уже существующие книги, но по оценке оттуда будет добавлено ещё около тысячи документов. 

В библиотеку дополнительно добавлены 1042 книги на военно-историческую тематику, все проименованы по нормальной схеме. Это книги из базы 150К. Из этой базы можно добавить достаточно много книг из раздела мемуаров и биографий. Можно проверить список 1042 на пересечения с базой Минюста. 
[1042.txt](https://github.com/terratensor/book-parser/files/12062423/1042.txt)

**Comment by iprst** [comment]
Отправил ссылку на дополнительные файлы. Там есть некоторое количество пересечений с текущей библиотекой, пока не обращаем на это внимания.

@audetv предлагаю уточнить алгоритм далее по сопоставлению имён файлов — что на выходе решаем получить? Сейчас список сопоставления файлов «старое имя — новое имя» представляет собой таблицу в гугле, которую после завершения можно экспортировать во что требуется. 

Мне отдать список или переименовать файлы и выгрузить их в облако?

**Comment by audetv** [comment]
> В библиотеку дополнительно добавлены 1042 книги на военно-историческую тематику, все проименованы по нормальной схеме. Это книги из базы 150К. Из этой базы можно добавить достаточно много книг из раздела мемуаров и биографий. Можно проверить список 1042 на пересечения с базой Минюста.
> [1042.txt](https://github.com/terratensor/book-parser/files/12062423/1042.txt)

Хорошо, сегодня проверю по списку. Если все ок, то добавляем эти 1024 книги к 7733 и выгружаю на сревер?

> @audetv предлагаю уточнить алгоритм далее по сопоставлению имён файлов — что на выходе решаем получить? Сейчас список сопоставления файлов «старое имя — новое имя» представляет собой таблицу в гугле, которую после завершения можно экспортировать во что требуется.
> 
> Мне отдать список или переименовать файлы и выгрузить их в облако?

Если мы отказались от карточек и имя книги в итоге будет содержаться в наименовании файлов, то тогда алгоритм простой, просто переименовываем файлы и дополнительных действий не надо. Далее новую БД с переименованными файлами обработаем и загрузим на сервер. Я загружу и поисковый индекс обновлю. Поэтому, если у вас уже есть готовый скрипт для переименования файлов, то вы можете сами переименовать, после обновляем архив 7733 
(дата сет милитеры). 

Если скрипта для переименования нет, то присылайте мне, я сделаю какую-нибудь программку и переименую файлы и выложу на диск, и обновлю индекс. 

Думаю 1024 файла и переименования имен файлов в 7733 надо связать и сделать одно обновление на сервере.

**Comment by iprst** [comment]
> Хорошо, сегодня проверю по списку. Если все ок, то добавляем эти 1024 книги к 7733 и выгружаю на сревер?

Если нет пересечений, то их добавим в общую базу вместе со всеми книгами, одним общим обновлением, как вы в конце пишете. 

> если у вас уже есть готовый скрипт для переименования файлов, то вы можете сами переименовать, после обновляем архив 7733

Файлы я обычно переименовываю штатными средствами тотал командера без специальных скриптов — нужно отобрать и отсортировать файлы по одному списку и скормить новые названия по второму списку. То есть я просто выложу переименованные файлы. 

Я убрал некоторое количество дубликатов, и наверное уберу ещё, но в принципе не сильно мешает, если дубликаты всё же попадаются. Постепенно можно отсеивать. 

По длинным параграфам надо забрать у Юрия те файлы, которые уже обработаны. Возможно помочь ему обработать хотя бы самые длинные, что-то он в одиночку там это делает, но пока мне надо переименовать до конца то что есть.

**Comment by iprst** [comment]
Переименовано 7138 книг.
Оставшиеся будут обрабатываться с неизвестной скоростью — поиск по именам файлов не выдаёт результатов.

**Comment by audetv** [comment]
Преобразовал список 1042.txt в  [1042.csv](https://github.com/terratensor/book-parser/files/12064639/1042.csv)
проверил на совпадения со списком Минюста — совпадений нет.

**Comment by iprst** [comment]
Все файлы переименованы. После удаления некоторых дубликатов из набора 7733 общее количество файлов — 7682. 
Список переименования прикреплён #28 
Самое длинное название 246 символов

В текущем наборе всё ещё есть дубликаты. Их около 80 штук. Примерно ещё около сотни будет после присоединения набора 1042 из базы К110. Пока я их не удалял, но это возможно.

**Comment by iprst** [comment]
Разбираюсь с теми книгами, которые опубликованы только в html. Их на самом деле не так уж много, в основном это либо стихи, которые нам сейчас бесполезны, либо дубликаты файлов из уже существующего набора.

**Comment by audetv** [comment]
> Все файлы переименованы. После удаления некоторых дубликатов из набора 7733 общее количество файлов — 7682.
> Список переименования прикреплён #28
> Самое длинное название 246 символов

Хорошо, новые файлы где можно скачать? Или какой алгоритм дальше, что делать? Я запутался. Что мне со списком делать?

> В текущем наборе всё ещё есть дубликаты. Их около 80 штук. Примерно ещё около сотни будет после присоединения набора 1042 из базы К110. Пока я их не удалял, но это возможно.

По поводу дубликатов, в ближайшее время выложу наработки на сервер, возможно сегодня. Я перечитывал документацию и нашел интересный способ нахождения похожих параграфов по весам слов в запросе. Я начинал поиск решения с задачи нахождения дубликатов текста, но мне кажется, что полученный способ можно использовать и для других сценариев (там ничего мной не придумано, все из доступной теории tf idf, веса слов, формулы, логарифмы — завораживает). Пока занимаюсь имитацией и копированием, и изучаю теорию, пытаюсь разобраться.

Как выложу на сервер, пришлю ссылку и напишу, про тот сценарий, который я пробовал помимо поиска дублей.

**Comment by iprst** [comment]
> Хорошо, новые файлы где можно скачать? Или какой алгоритм дальше, что делать? Я запутался. Что мне со списком делать?

Файл выложил в качестве бэкапа. Я доделаю html сортировку, и выложу все docx сразу в один заход.

**Comment by iprst** [comment]
> По поводу дубликатов, в ближайшее время выложу наработки на сервер, возможно сегодня. Я перечитывал документацию и нашел интересный способ нахождения похожих параграфов по весам слов в запросе. Я начинал поиск решения с задачи нахождения дубликатов текста, но мне кажется, что полученный способ можно использовать и для других сценариев (там ничего мной не придумано, все из доступной теории tf idf, веса слов, формулы, логарифмы — завораживает). Пока занимаюсь имитацией и копированием, и изучаю теорию, пытаюсь разобраться.

Годно. В принципе можно даже начать с более простого сценария — сравнивать не параграфы, а имена файлов. Есть легитимная похожесть — когда многотомник и указаны разные тома (части, книги и тд) одного издания, и есть нелигитимная похожесть, когда речь идёт о дублированных книгах, по разному обработанных и слегка отличающихся названием (отсутствует издательство, пропущен инициал автора или не указан год, и тд). Мне кажется это похожего типа задачи, только строка короче.

**Comment by iprst** [comment]
> все из доступной теории tf idf, веса слов, формулы, логарифмы

В процессе набивания руки на милитере, обнаружил что несмотря на внешнюю корректность приводимых карточек, в действительности там творится полнейший чёртичё. У карточек шесть или семь разных форматов. Файлы **_разных_** книг имеют **_одинаковое_** название (!), это была боль. Также есть абсолютно одинаковые файлы (побитово идентичные), названные разными именами, иногда лежат в разных разделах, иногда изображают из себя разные тома одного издания, и так далее. 

Методика наименований файлов абсолютно какая угодно. Некоторые файлы легко ищутся по имени, некоторые таким образом найти в принципе невозможно. Неалгоритмизируемая куча-мала. 

Это я почему к tf idf — зря люди кластеризируют информацию до того, как узнали что за информация у них получается: в итоге всегда выходит попытка впихивания невпихуемого в сетку критериев, а с учётом многолетнего процесса критерии могут многократно видоизмениться и перестать наследовать что угодно из прошлого. Поэтому надо кластеризировать реальный корпус, а не заранее изобретать фантазию о нём. Этот вопрос шире книг, он и в геоматрице по полной, и где угодно.

**Comment by audetv** [comment]
> > интересный способ нахождения похожих параграфов по весам слов в запросе. Я начинал поиск решения с задачи нахождения дубликатов текста, но мне кажется, что полученный способ можно использовать и для других сценариев
> 
> Опять же, из ранее обсуждавшегося — у нас есть «словарь сущностей», против которого мы можем тестировать корпус текста. Один из вариантов применения tf idf и производных. Среди сущностей у нас уже есть топонимы, есть даты, и тд.

Совершенно верно, я думаю мы сможем найти применение. 
Я пока точно не знаю почему так произошло, не ожидал, просто я когда это начал делать, в теории вроде все понятно и скучно, но когда сделал пробный вариант на коленке, без особой надежды, нажал кнопку, получил результат,  и это были совсем другие ощущения, как вы в комментариях к геоматрице, вроде в теме про Бейрут писали, появился приятный мандраж открытия.. в данном случае, открытие — чисто внутреннее ощущение, калейдоскоп не просто сломался его разнесло в клочья, и пошли эмоции и мысли и в голову, я до сих пор еще не во всем разобрался.

Например, я брал некоторые выдержки — предложения из даты в истории, которую делает Александра и производил поиск и почти всегда были найдены подходящие параграфы, но предложение должно  быть не коротким, чтобы это имело хороший результат, иначе логичнее обычным поиском искать. 

Например:
> 1826 — преобразование «Особой канцелярии» при Министерстве внутренних дел в III отделение собственной Его Императорского Величества канцелярии.

Наилучшее совпадение:

> Доложена составленная по распоряжению Главного Начальника Верховной Распорядительной Комиссии записка об организации розыскной части в С.-Петербурге по делам политическим. Сущность излагаемых в записке мер заключается в сосредоточении розыскных действий, возложенных ныне на два самостоятельных учреждения: III Отделение Собственной Его Императорского Величества Канцелярии и Секретное Отделение при Управлении С.-Петербургского Градоначальника, в одном установлении. С этою целью из ведения III Отделения выделяется секретное наблюдение по С.-Петербургу и передается в ведение С.-Петербургского Градоначальника с присоединением, вдобавок к имеющимся ныне средствам Секретного Отделения Градоначальства, по 61 000 р. в год из сумм III Отделения. При устанавливаемом преобразовании Секретное Отделение, оставаясь подчиненным Градоначальнику, получает характер постоянного учреждения, ответственного за исполнение возлагаемых на него обязанностей. В видах же согласования между собою деятельности названного Отделения, с одной стороны, и III Отделения Собственной Его Императорского Величества Канцелярии, с другой, устанавливается следующий порядок взаимных между ними отношений: 1) III Отделение сообщает Градоначальнику все те свои сведения, которые могут вызвать или облегчить наблюдательные розыскные действия по городу;

И далее:

> 1826, 3 (15) июля — преобразование Особой канцелярии Министерства внутренних дел в Ш Отделение Его Императорского Величества Канцелярии.

Или запрос:

> 1099 — Первый крестовый поход: взятие Иерусалима крестоносцами.
> == последовала беспощадная резня, а Готфрид Бульонский принял титул Защитника Гроба Господня

Один из результатов:

> Однако князья, со своей стороны, требовали, чтобы власть над Иерусалимом была вручена одному из них. Страсти разгорелись, и распря достигла такой остроты, что крестоносцы едва не оказались на пороге настоящей междоусобной войны. В конце концов главари крестоносцев пришли к компромиссному решению. Формально Иерусалим был передан в управление представителю римского папы — патриарху Даимберту, а из числа князей был избран фактический государь Иерусалима — Готфрид Бульонский, которому присвоили пышный титул «защитника гроба господня». Готфрид согласился даже признать себя вассалом патриарха: не стоило из-за этой формальности ссориться с церковью! Ведь реальная сила все равно была не на стороне духовенства, хотя оно и претендовало на всю полноту власти в Иерусалиме.

Вроде бы и ничего такого, но при понимании как это работает, понимании теории и ощущая на практике, интересные мысли в голове зарождаются.

**Comment by audetv** [comment]
Я обязательно в ближайшее время размещу, что бы каждый (наверное пока из закрытого списка, т.к.) смог потрогать и ощутить результат, для меня именно реальный результат оказал шокирующее воздействие.

**Comment by audetv** [comment]
Его можно прикрутить к поисковику, все работает из мантикоры на нашей базе, подготовительный расчет делается в программе и отправляется запрос в БД на основе расчета, т.е. можно буквально сделать второй(иной) режим поиска, галочкой или еще как — это детали. Я думал пока разместит в сыром виде для оценки, как брал из примера, но пример переделанный и исправленный для нашей БД и я в примере, пока разбирал код и теорию, покопался немного. Все это можно прямо в поисковик прикрутить, после оценки н решения. 

И да похожие новости можно так искать, в теории, пока не проверить т.к. у нас нет базы новостей. Но это будет работать. Можно будет прямо находить все одинаковые перепощенные, немного изменённые новости и докопаться до источника.

**Comment by iprst** [comment]
> И да похожие новости можно так искать, в теории, пока не проверить т.к. у нас нет базы новостей. Но это будет работать. Можно будет прямо находить все одинаковые перепощенные, немного изменённые новости и докопаться до источника.

Скорее имею в виду что есть новости, в которых по сути пересказаны древние факты или сценарии, они будут вылазить потому, что корпуса текстов, против которого это новости бы проверялись скажем их авторами, как-бы не существует. Тут вопрос именно к «корпусу текстов» как к матрице из которой черпают: есть много локальных или глобальных баз, но скорее они представляют собой либо узкое направление, либо бесполезный пользовательский веб-два-ноль. 

> все работает из мантикоры на нашей базе, подготовительный расчет делается в программе и отправляется запрос в БД на основе расчета, т.е. можно буквально сделать второй(иной) режим поиска

Супер.

**Comment by iprst** [comment]
Загружаю набор 8724 на гугл диск. ZIP на 3 с копейками ГБ. 
Пока без порезанных длинных параграфов.
Пока без склеенных html книг.

**Comment by audetv** [comment]
Отправил письмо со ссылкой. Наверное, можно эту ссылку и не скрывать, пока решил так сделать, но совершенно не против полного раскрытия информации.

Загрузил для тестирования пробный вариант поиска похожих параграфов. Поиск по умолчанию работает по content (text), по наименование книги пока не работает, мы ранее отключили индексацию по имени книги. Я думаю, когда буду переделывать индекс добавлю индексацию по имени, и переделаю запросы в поиске, отключу поиск по этому полю в поисковике, должно сработать. Тогда это поле останется проиндексированным, но в поиск будет попадать только в запросах, в которых явно указано, что надо искать и в поле наименование книги.

В настройках по умолчанию включены стоп русские слова. Enable stopwords (RU)

Enable boost on words based on tdidf добавляет веса к запросу, это видно в строке запроса под строкой — всего найдено.

Perform boolean instead of quorum - слова в запросе через оператор или
Про режим поиска quorum — [Quorum-matching-operator](https://manual.manticoresearch.com/Searching/Full_text_matching/Operators#Quorum-matching-operator)
Minimum words to match(as float between 0.1 and 1.0) - добавляет указанное значение как кворум оператор, видно в запросе
```
SELECT *,WEIGHT() as w FROM common_library WHERE MATCH('@text "баас^18.507860701144 2003^12.219942773623 1968^11.702494149546 ираком^9.1704897868129 ираке^9.1704897868129 июльской^9.1573550851184 переворота^7.887803274129 партия^7.8125110068429 называлась^6.2375782179005 революцией^6.0749396278163 гг^5.9115321386237 пришла^5.546478664012 ходе^5.302232259614 власти^5.2965542746873 правила^5.022881430336 года^3.9555430396587"/0.2') LIMIT 0,20 OPTION ranker=expr('sum(atc*1000)'), idf='plain,tfidf_unnormalized',field_weights=(book_name=1,text=1);
```

`года^3.9555430396587"/0.2') ` - /0,2 кворум оператор и означает, что по крайней мере 20% из 16 слов в запросе должны совпадать

Ещё в примере были ranker я их просто добавил как есть, но пока не разбирался, не могу написать различия, по некоторым по наименованиям в принципе понятно, что происходит, а вот режимы `proximity_bm25`, `bm25`, `sph04` — пока в процессе.

**Comment by iprst** [comment]
С новостями получается очень интересное «гадание на кофейной гуще» — в результатах можно сказать, что «примерно то же самое что в гугле», однако если вычесть из «гугла» абсолютно весь бездумный веб-два-ноль, твиттер и прочий бред соцсетей и «новостей». То есть гугл был бы полезным инструментом, если бы не мусор. А у нас получается полезный.

**Comment by iprst** [comment]
> Minimum words to match(as float between 0.1 and 1.0) - добавляет указанное значение как кворум оператор (…)  по крайней мере 20% из 16 слов в запросе должны совпадать

Есть предположение что этот оператор должен быть динамическим критерием для рейтинга: чем выше у результата кворум-оператор, при котором этот результат находится, тем больший рейтинг назначается этому результату.

**Comment by audetv** [comment]
> Пока надо в тестовом режиме — ничего не понятно по выходу, иногда результаты полезные, иногда чушь, ранжирование тоже спорное, почти каждый раз нужно искать наиболее адекватный режим. Будем смотреть. Надо описать по максимуму и отправить товарищам на тест.

Как бы и да. Основной сценарий без кручения ручек и параметров, это нажать на ссылку «Найти похожий» под параграфом, эта ссылка позволяет искать похожие параграфы и дубли. Если начинаем крутить ручки, то тут результат будет зависеть от параметров и от запроса. Т.е. в этом режиме надо понимать, что делаешь и зачем, и этот режим в таком виде не для каждого пользователя подойдет — сложно. Так можно дать консоль от мантикоры и мануал и вперед пишите запросы в БД)) Я поэтому и писал, что если мы найдем сценарии использования, то можем добавить в общее пользование, но для понимающих как работает, предполагаю этот режим может быть полезен. И это поиск не по1-2-3 словам, а по предложениям, на словосочетаниях работает не очень. (Проверяю)

Пришла аналогия в голову, что в коммерческом кейсе в таких случаях пишут мануалы, статьи в блог, проводят презентации и обучение пользованием системы (делают курсы, онлайн университеты и пр.) и продают такой режим, как что-то особо ценное и важное. Тут акцент не на сам наш режим, а на процесс.

Возможно да, надо расписать так, чтобы было понятно обычному не в теме человеку, как пользоваться, но для неподготовленного человека, как не напишешь, он скорее всего сразу не сможет осознать написанное. Я вот как обычный человек, мануал мантикоры с апреля читаю и каждый раз что-то новое нахожу) Но что делать. Со сценариями использования будет проще.

> Есть предположение что этот оператор должен быть динамическим критерием для рейтинга: чем выше у результата кворум-оператор, при котором этот результат находится, тем больший рейтинг назначается этому результату.

Про кворум я понял буквально как написано, что это кол-во слов(term), 0.2 по умолчанию — 20% от заданного кол-ва слов в поисковом запросе, которые должны совпадать, похоже, что это минимальная граница от 20% и выше. 

> чем выше у результата кворум-оператор, при котором этот результат находится, тем больший рейтинг назначается этому результату.

Вот эта фраза для меня не понятна, звучит как рекурсия, я понимаю, что кворум оператор применяется к запросу, а не к результату запроса. Я выше написал как я понимаю, как это влияет на результаты. И вес каждого результата складывается не только от кворум. Ещё выбор формулы ranker влияет на запрос, и это видно при смене ranker , это отображается в тексте запроса. Сами rankers описаны [тут](https://manual.manticoresearch.com/Searching/Options#ranker), буду изучать. [Sorting and ranking](https://manual.manticoresearch.com/Searching/Sorting_and_ranking#Sorting-and-ranking)

Из того что заметил:
Если выставить кворум 1.0 (надо указать именно 1 точка 0 ), то будет выборка меньше (Minimum words to match(as float between 0.1 and 1.0).
Все значения с единицей надо писать как один точка ноль — 1.0

Cut-off factor - percent of best match weight, (нужно так же указывать как float 0.1 - 1.0) не влияет на результаты запроса, это  только внешнее отображение, как будет окрашен серым цветом текст результатов поиска.

Например, сбросьте поиск, кнопкой сбросить и введите фразу:
```
чтобы Германия никогда больше не угрожала своим соседям
```

При значениях по умолчанию будут бредовые результаты, но если отключить стоп слова, то уже будет множество попаданий. А если выставить Minimum words to match(as float between 0.1 and 1.0) — 1.0 (кворум 100%), то будет 25 результатов и все результаты именно с этой фразой.

Но в тексте этого запроса нет стоп-слов - предлогов, союзов. Заметил, когда во фразе встречаются в, и и прочие, то результат забивается этими предлогами, надо подумать, и как то снижать вес этих предлогов.

Т.е. для разных параграфов стоп слова дают разные результаты. Но как пишут в теории поиска, что мы точно не знаем, что ищет человек который написал поисковый запрос))) можем предполагать.

Есть предположение, буду проверять, что режим поиска по умолчанию в поисковике (query_string) это коврум /3
так пишут примеры в мануале. У меня вопрос для проверки к «тройке» не похоже. И есть предположение, что в текущем тестовом режиме поиска можно сделать и query_string запрос, то что по умолчанию включено в поисковике. 

И например, если слов в запросе больше 4-5 (надо определить это значение) и не будет найдено результатов, то предлагать пользователю перейти в другой режим поиска в тот, что тестируем, т.к. это даст больше совпадений. 

Кстати если набрать [чтобы Германия никогда больше не угрожала своим соседям](https://lib.svodd.ru/?search%5Bquery%5D=%D1%87%D1%82%D0%BE%D0%B1%D1%8B+%D0%93%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D1%8F+%D0%BD%D0%B8%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0+%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B5+%D0%BD%D0%B5+%D1%83%D0%B3%D1%80%D0%BE%D0%B6%D0%B0%D0%BB%D0%B0+%D1%81%D0%B2%D0%BE%D0%B8%D0%BC+%D1%81%D0%BE%D1%81%D0%B5%D0%B4%D1%8F%D0%BC&search%5Bmatching%5D=&search%5Bmatching%5D=query_string) в обычном нашем режиме поисковика, то будет 25 совпадений, столько же будет если применить кворум 1.0 без стоп-слов в тестовом режиме.

В общем буду разбираться с rankers и запросами, получил level up и пока впереди темный лес)

**Comment by audetv** [comment]
Я думаю, нам для наших исследования это режим точно пригодиться, во всяком случае мне стало понятно, как можно составлять очень сложные запросы в поиск. И мы можем применять для наших исследований разные запросы и смотреть, что будет давать наилучший результат, а там уже и до машинного обучения дойдет...

**Comment by audetv** [comment]
Еще заметил, что длинные параграфы могут сломать результаты, особенно с выключенными стоп словами, так что с такими параграфами 110% надо разбираться, готовлюсь) 

Если в обычном поиске, мне почти ни разу не попались длинные параграфы, то в таком режиме они встречались довольно часто. И такую портянку текста просто не объять взором, просто стразу появляется желание промотать к следующему результату, иногда приходилось долго проматывать, на телефоне вообще огонь))

 Но это бы ладно, мне кажется, что ещё длинные параграфы ломают формулы, коротких нормальных параграфов много больше, чем длинных и частота появления слов в документе может стать неадекватной, не знаю может показалось, не проверял формулами, пока на уровне интуиции.

**Comment by audetv** [comment]
> Загружаю набор 8724 на гугл диск. ZIP на 3 с копейками ГБ.
> Пока без порезанных длинных параграфов.
> Пока без склеенных html книг.

Не знаю где найти эти фалы, предыдущая ссылка не работает, новую не могу найти. 
Это я так понимаю 2 комплекта в сумме ~(7733 книги + 1042) 1042 из недавно выгруженных флибусты?

**Comment by iprst** [comment]
> Не знаю где найти эти фалы, предыдущая ссылка не работает, новую не могу найти.

Название папки — mt_book_base_rename 
Скоро я туда догружу обработанные html, они почти готовы. 
Да, 1042 это те которые проверялись по названиям по Минюсту.

**Comment by audetv** [comment]
> > Не знаю где найти эти фалы, предыдущая ссылка не работает, новую не могу найти.
> 
> Название папки — mt_book_base_rename Скоро я туда догружу обработанные html, они почти готовы. Да, 1042 это те которые проверялись по названиям по Минюсту.

Понял, нашел, спасибо.

**Comment by iprst** [comment]
> Подумал, что если взять из любого предложения вычленить суть — 2-3 слова и набрать в поиске, то адекватных результатов будет достаточно и в обычном режиме поиска. Надо просто уметь разбивать обычные и сложные предложения на составляющие и искать, думаю таким то навыком должно обладать большее кол-во людей, чем пониманием NLP, tf-idf bm25 и прочего из теории поиска. Так что да, режим спорный, но для меня он приоткрыл понимание тех вещей, которые не входили в мои понятия, теперь я на них обратил свое внимание.

Всё именно так и обстоит, однако тут хитрость — понять, что запрос нужно составлять каким-то вполне определённым образом по некой методике можно лишь двумя способами: (а) самостоятельно, подумав или исходя из опыта и (б) воспользовавшись оракулом, в теории вычислительной сложности оракул представляет собой некую «строку», которая позволяет понизить ранг вычисляемой задачи, чтобы она стала доступнее. Так вот вся эта NLP tf-idf и остальная теория поиска и есть такой оракул для «упрощения понимания того, как нужно составить запрос». То есть это очевидно, что из текста нужно выкинуть предлоги и частотные слова (что-то вроде стоп-слов с добавкой) — так, что в какой-то момент останутся только _целевые_ слова. И тут самый смак — задача практически невычислима без оракула, поскольку если дано _n_ слов, то из них можно составить _n!/m!·(n-m)!_ сочетаний без повторений, а факториальные задачи по определению одни из самых ресурсоёмких и большая их часть невычислима текущими средствами. 

Оракул позволяет делать предположения и проверять их, тем самым можно накопить некий вычислительный опыт (то есть прописать какие-то схемы в нейросетях собственной головы), и далее им воспользоваться как интуицией. Суть явления намного шире, чем обсуждаемый вопрос, это фундаментальное правило и в целом любая «теория» является оракулом для соответствующей «практики», в свою очередь в начале любая «теория» это «гипотеза», которая в свою очередь «наблюдение за фактором среды». Управление повсюду.

**Comment by iprst** [comment]
> Еще заметил, что длинные параграфы могут сломать результаты, особенно с выключенными стоп словами, так что с такими параграфами 110% надо разбираться, готовлюсь)

Юрий какую-то часть [параграфов](https://github.com/terratensor/book-parser/issues/23) уже обработал. Писал выше — надо ему помочь будет, закончить эту задачу. 

> Если в обычном поиске, мне почти ни разу не попались длинные параграфы, то в таком режиме они встречались довольно часто. И такую портянку текста просто не объять взором, просто стразу появляется желание промотать к следующему результату, иногда приходилось долго проматывать, на телефоне вообще огонь))

Мне они в первый раз надоели ещё в постмане, где по какой-то причине попадается пара длинных параграфов на достаточно много запросов. Эти параграфы оказались неразмеченными главами одной книги — вместо жёстких переносов там мягкие, которые парсер не воспринял как перенос. Или что-то подобное, что выглядит так. Абзацы есть, переноса нет. Собственно тогда и родилась задача — даже на ящике нужно долго мотать мышкой. Ужас.

> Но это бы ладно, мне кажется, что ещё длинные параграфы ломают формулы, коротких нормальных параграфов много больше, чем длинных и частота появления слов в документе может стать неадекватной, не знаю может показалось, не проверял формулами, пока на уровне интуиции.

С точки зрения того, что у нас в системе параграф определеяет расстояние между поисковыми словами (это расстояние не должно превышать количество символов в параграфе) — возникает привычка, что «всё находится» = «всё находится рядом». Это не баг, а фича. А длинные параграфы эту привычку ломают, поскольку позволяют искать слова на разных концах строки. Предполагаю, что опции в этом новом методе, связанные с расстоянием, были изначально предназначены для обеспечения функционала, который мы возложили на параграфы. Например ограничить поисковую единицу страницей или строкой. Что как-бы верно, но мне наш вариант нравится больше, потому что он согласуется с естественной сутью текста как набора параграфов. Если поискать сразу во всей книге с опцией «не далее чем столько символов», думаю деление на параграфы, возможно 2-3 параграфа, это будет наиболее оптимальным вариантом поиска. Это можно проверить. Про поиск в двух или трёх параграфах мы говорили ещё в начале. Но думаю на текущий момент и с одним всё в порядке.

**Comment by iprst** [comment]
> Я думаю, нам для наших исследования это режим точно пригодиться, во всяком случае мне стало понятно, как можно составлять очень сложные запросы в поиск. И мы можем применять для наших исследований разные запросы и смотреть, что будет давать наилучший результат, а там уже и до машинного обучения дойдет...

Разумеется пригодится. Я не имел в виду что это бесполезный инструмент, он как раз очень полезный. Только не как сервис на сайте, не в его текущем представлении, где пока ничего не понятно. Это инструмент исследований, а не пользовательский интерфейс — до интерфейса ему ещё потребуется дорасти. 

А вот пользоваться им и даже опубликовать решение на отдельном поддомене вполне реально. Для тестов можно сделать какой-то сервис отметок — пользователь забросил свой параграф, настроил поиск или поискал по умолчанию, и отмечает результаты которые работают (или наоборот плохие). Результаты отдаются в какую-то таблицу, где есть текст запроса, настройки запроса и результаты, которые отмечены. Так на этих данных можно приступать к обучению нейросети.

**Comment by iprst** [comment]
> 2 комплекта в сумме ~(7733 книги + 1042)

Теперь три комплекта — добавил ещё 2784 книги, переведённых из html в docx. Не проверял на дубликаты, вернее были проверены только самые явные методы. Думаю дубликаты в наличии. Возможно прогнать из кажой книги один случайный параграф через новый сервис и получить список дублированных книг.

**Comment by iprst** [comment]
Задача по сопоставлению имён файлов и названий книг выполнена. Файлы выгружены, в пулл-реквестах опубликованы два списка с названиями книг. 

Общее количество книг в военно-исторической библиотеке — 11508.
Ожидается какое-то количество дубликатов, но это уже другая задача.
Продолжаем работу по [разбиению](https://github.com/terratensor/book-parser/issues/23) длинных параграфов.
