### ISSUE TITLE
Ошибка при обработке docx файла

### ISSUE THREAD

**Issue by audetv** [terratensor/book-parser#30]
Ошибка: panic: XML syntax error on line 2: illegal character code U+000B

```
panic: XML syntax error on line 2: illegal character code U+000B

goroutine 1 [running]:
github.com/audetv/book-parser/common/app/starter.(*App).Parse(0xc00dc59f28, {0x10502a8, 0xc000227080}, 0x167e, {0x1050350, 0xc0006de310}, {0xc000116090, 0x4})
        C:/Users/agusev/GolandProjects/book-parser/common/app/starter/starter.go:65 +0x716
main.main()
        C:/Users/agusev/GolandProjects/book-parser/common/cmd/main.go:99 +0x648
```

<details><summary>Details</summary>
<p>

![2023-07-19_12-29-06](https://github.com/terratensor/book-parser/assets/10896447/90908a7f-8673-4595-b68f-c3a3c03d7289)

</p>
</details> 

Ошибка произошла при обработке файла: Лассуэлл Гарольд — Техника пропаганды в мировой войне.docx
из нового набора, до возникновения этой ошибки было успешно обработано 5758 файлов.

Этот файл так же не открывается редактором word

В структуре xml присутствует запрещенный символ U+000B — вертикальной табуляции

Думаю, что с этим делать, пока не знаю сколько таких файлов. 

Есть мысль при обработке записать проблемные файлы в отдельный файл ошибок, получить список этих файлов и уже разбираться с ними.

**Comment by audetv** [comment]
> Есть мысль при обработке записать проблемные файлы в отдельный файл ошибок, получить список этих файлов и уже разбираться с ними.

Сделал обработку ошибок и запись их в файл. Обработал все файлы 11360.
В итоге ошибка была зафиксирована только в одном файле: Лассуэлл Гарольд — Техника пропаганды в мировой войне.docx

`Лассуэлл Гарольд — Техника пропаганды в мировой войне.docx , XML syntax error on line 2: illegal character code U+000B`

Остальные файлы успешно обработаны

**Comment by iprst** [comment]
> В структуре xml присутствует запрещенный символ U+000B — вертикальной табуляции

Проблемный символ не удалось найти никакими средствами. Ворд указывает на номер символа и строку, но там ничего запретного нет. PowerGREP не ищет никаких комбинаций, которые бы отвечали за вертикальную табуляцию, в файле не видно такого. Sublime открывает файл, и тоже не видит ничего запретного. 

Файл был распознан с pdf в автоматическом режиме. Вручную распознал его по-новой и сохранил в docx без оформления — всё равно не помогло. Какой-то внутренний глюк Finereader конкретно с одним этим файлом (распознаны тысячи). Сохранив распознанное в rtf формате удалось спокойно открыть в ворде и пересохранить в docx. Добавил дополнительный файл в ту же папку на диске.

**Comment by audetv** [comment]
Успешно запустил на локальной машине.
Итог обработки:

<details><summary>Details</summary>
<p>

![2023-07-19_14-53-24](https://github.com/terratensor/book-parser/assets/10896447/19451fff-5948-4e14-86c0-01b6c4a12ba2)
![2023-07-19_14-54-25](https://github.com/terratensor/book-parser/assets/10896447/d102df2c-25e3-4a51-bc9d-0a82b9b2bf04)

</p>
</details> 

Итоговый размер БД ~47Гб

**Comment by iprst** [comment]
Мантикора 32,6 Гб — такую уже не передать через гугл-диск, даже пожатая будет весить более 16 Гб.

**Comment by audetv** [comment]
Файл успешно обработан.
