### ISSUE TITLE
Конвертация fb2 в docx

### ISSUE THREAD

**Issue by iprst** [terratensor/book-parser#37]
В процессе конвертации обнаружены проблемные места. 

Использую Word — открываю пустой документ и запускаю скрипт VBA:
```
Sub ConvertDocToDocx()
    Dim xDlg As FileDialog
    Dim xFolder As Variant
    Dim xFileName As String
    Application.ScreenUpdating = False
    Set xDlg = Application.FileDialog(msoFileDialogFolderPicker)
    If xDlg.Show <> -1 Then Exit Sub
    xFolder = xDlg.SelectedItems(1) + "\"
    xFileName = Dir(xFolder & "*.fb2", vbNormal)
    While xFileName <> ""
        Documents.Open FileName:=xFolder & xFileName, _
            ConfirmConversions:=False, ReadOnly:=False, AddToRecentFiles:=False, _
            PasswordDocument:="", PasswordTemplate:="", Revert:=False, _
            WritePasswordDocument:="", WritePasswordTemplate:="", Format:= _
            wdOpenFormatAuto, XMLTransform:=""
        ActiveDocument.SaveAs xFolder & Replace(xFileName, "fb2", "docx"), wdFormatDocumentDefault
        ActiveDocument.Close
        xFileName = Dir()
    Wend
    Application.ScreenUpdating = True
End Sub
```

При запуске он спрашивает папку с исходниками fb2, и далее без остановки в автоматическом режиме перебирает fb2 файлы и сохраняет их как docx. В принципе работает быстро, на документ уходит в среднем 1,5 секунды. Однако вследствие того, что в тексте используются запрещённые символы, скрипт выдаёт ошибку и останавливается. По какой-то причине дикие тёмные редакторы текстов используют треугольные скобки в самых произвольных местах прямо в тексте, в результате парсер пытается обработать скобку и идущий за ней текст как тег (!) и очевидно падает. Также не читаются символы типа амперсанда, а вследствие того, что в тексте часто символы представлены их кодовым обозначением, типа `&nbsp;` возникает ошибка. 

Общий алгоритм действий в целом такой — скрипт в окне ошибки показывает имя файла и строку с номером символа, который вызвал ошибку. Этот файл открывается в редакторе типа Sublime и в нём правится конкретное место с ошибкой. В принципе, практически все ошибки можно было бы устранить, пройдясь regex-ом в PowerGREP по всем файлам, но поскольку весь набор ошибок неизвестен, а большинство файлов обрабатываются без ошибок, эта затея под вопросом. 

Возможно нужно как-то изменить скрипт, чтобы он при получении ошибки пропускал файл и обрабатывал следующий, таким образом в конце процедуры останется набор необработанных файлов, которые уже в отдельности можно будет пытаться обработать в пакетном режиме в PowerGREP. Насколько я вижу в самом скрипте нет никакого обработчика ошибок, то есть вся проблема возникает в других модулях программы.

**Comment by iprst** [comment]
До слёз:

![image](https://github.com/terratensor/book-parser/assets/129882753/f0fbeae0-ac67-432e-98cf-f0956e2e0e6b)

И ведь не врёт:

![image](https://github.com/terratensor/book-parser/assets/129882753/05ecf420-558d-4d73-9440-64ee3c8ba731)

Вот примерно в такой возне проходит конвертация. Если бы не ошибки, то за пару суток всё обработалось бы само. С ошибками неизвестно сколько.

**Comment by audetv** [comment]
Да уж, забавно.
Посмотрел код 3 раза, ничего в нем не вижу, такого, чтобы смог исправить, ощущение, что все основное действие происходит тут:

```
 Documents.Open FileName:=xFolder & xFileName, _
            ConfirmConversions:=False, ReadOnly:=False, AddToRecentFiles:=False, _
            PasswordDocument:="", PasswordTemplate:="", Revert:=False, _
            WritePasswordDocument:="", WritePasswordTemplate:="", Format:= _
            wdOpenFormatAuto, XMLTransform:=""
```

но что это значит мне не понятно, я с vba вообще не имею опыта., похоже, что тут просто параметры перечисляются, а где вся магия не понятно) возможно есть какой-то параметр отвечающий за это, но это все предположение. Пока не знаю, что с этим делать.

**Comment by iprst** [comment]
> похоже, что тут просто параметры перечисляются, а где вся магия не понятно)

Думаю ошибка отдаётся стандартная, не скриптом, а VBA машиной ворда. То есть для её обработки скрипт должен перехватывать эту ошибку. В общем, кажется на коленке не сочиню, VBA не знаю вообще, еле нашёл место куда вставлять скрипт.

**Comment by iprst** [comment]
Небольшое изменение в коде позволят выполнять его с игнорированием всех ошибок. Добавляется второй строкой выражение: 

```
Sub ConvertDocToDocx()
On Error Resume Next
```
Работает как часы, ошибки проигнорированы, обработано уже более трети всех файлов. 
Затем по списку готовых docx фильтруются исходные fb2 и не обработанные файлы поступают на второй этап обработки.

**Comment by iprst** [comment]
Методом `On Error Resume Next` и последующими дополнительными обработками завершён экспорт всех fb2 книг в формат docx. 

100908 книг конвертировано.
15 книг имеют битые данные, их позже придётся восстановить из архивов.
Было 67 Гб fb2, стало 25 Гб docx. 
_________
Также есть книги, экспортированные из текстовых форматов в docx.
Их количество 10795. 

Идёт распознание сканов djvu и pdf. 
На текущий момент распознано 6602 файла, впереди ещё 27085 сканов. 

Итого в настоящий момент в формате docx собрано 118305 файлов. 
Их список #40 опубликован для контроля данных.
